name: build and test

defaults:
  run:
    shell: bash -exo pipefail {0}

on:
  workflow_call:
    inputs:
      compiler_exe: {type: string, required: true}
      std: {type: string, required: true}
      gpu_build_archs: {type: string, required: true}
      cpu: {type: string, required: true}
      test_name: {type: string, required: false}
      build_script: {type: string, required: false}
      test_script: {type: string, required: false}
      run_tests: {type: boolean, required: false, default: true}
      container_image: {type: string, required: false}

jobs:
  build:
    if: inputs.build_script != '' && inputs.container_image != ''
    name: Build ${{inputs.test_name}}
    uses: ./.github/workflows/run-as-coder.yml
    with:
      name: Build ${{inputs.test_name}}
      runner: linux-${{inputs.cpu}}-cpu16
      image: ${{inputs.container_image}}
      command: |
        ${{ inputs.build_script }} "${{inputs.compiler_exe}}" "${{inputs.std}}" "${{inputs.gpu_build_archs}}"

  test:
    needs: build
    if:  ${{ !cancelled() && ( needs.build.result == 'success' || needs.build.result == 'skipped' ) && inputs.test_script != '' && inputs.container_image != '' && inputs.run_tests}}
    name: Test ${{inputs.test_name}}
    uses: ./.github/workflows/run-as-coder.yml
    with:
      name: Test ${{inputs.test_name}}
      runner: linux-${{inputs.cpu}}-gpu-v100-latest-1
      image: ${{inputs.container_image}}
      command: |
        nvidia-smi
        ${{ inputs.test_script }} "${{inputs.compiler_exe}}" "${{inputs.std}}" "${{inputs.gpu_build_archs}}"
