name: Build Windows

on:
  workflow_call:
    inputs:
      test_name: {type: string, required: false}
      build_script: {type: string, required: false}
      container_image: {type: string, required: false}

jobs:
  prepare:
    name: Build ${{inputs.test_name}}
    runs-on: windows-2022
    permissions:
      id-token: write
      contents: read
    env:
      SCCACHE_BUCKET: rapids-sccache-devs
      SCCACHE_REGION: us-east-2
      SCCACHE_IDLE_TIMEOUT: 32768
      SCCACHE_S3_USE_SSL: true
      SCCACHE_S3_NO_CREDENTIALS: false
    steps:
      - name: Get AWS credentials for sccache bucket
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::279114543810:role/gha-oidc-NVIDIA
          aws-region: us-east-2
          role-duration-seconds: 43200 # 12 hours)
      - name: Fetch ${{ inputs.container_image }}
        shell: powershell
        run: docker pull ${{ inputs.container_image }}
      - name: Fetch the repository
        shell: powershell
        run:  docker run ${{ inputs.container_image }} powershell -c "git clone https://github.com/NVIDIA/cccl.git;
                                                                      cd cccl;
                                                                      git fetch --all;
                                                                      git checkout ${{github.ref_name}};
                                                                      ${{inputs.build_script}};"
