name: Dispatch build and test

on:
  workflow_call:
    inputs:
      per_cuda_compiler_matrix: {type: string, required: true}
      build_script: {type: string, required: false}
      test_script: {type: string, required: false}
      devcontainer_version: {type: string, required: true}

jobs:
  # Using a matrix to dispatch to the build-and-test reusable workflow for each build configuration
  # ensures that the build/test steps can overlap across different configurations. For example,
  # the build step for CUDA 12.1 + gcc 9.3 can run at the same time as the test step for CUDA 11.0 + clang 11.
  build_and_test:
    name: ${{matrix.cpu}}
    uses: ./.github/workflows/build-and-test.yml
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.per_cuda_compiler_matrix) }}
    with:
      cpu: ${{ matrix.cpu }}
      test_name: ${{matrix.compiler.name}}${{matrix.compiler.version}}/C++${{matrix.std}}
      build_script: "${{ inputs.build_script }} ${{matrix.compiler.exe}} ${{matrix.std}} ${{matrix.gpu_build_archs}}"
      test_script:  "${{ inputs.test_script }}  ${{matrix.compiler.exe}} ${{matrix.std}} ${{matrix.gpu_build_archs}}"
      run_tests: ${{ contains(matrix.jobs, 'test') && !contains(github.event.head_commit.message, 'skip-tests') && matrix.os != 'windows' }}
      container_image: rapidsai/devcontainers:${{inputs.devcontainer_version}}-cpp-${{matrix.compiler.name}}${{matrix.compiler.version}}-cuda${{matrix.cuda}}-${{matrix.os}}

